name: Build and Deploy Go App to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24' # Adjust to your Go version

      - name: Run tests
        run: go test ./...

      - name: Create .env file
        # run: echo "API_KEY=${{ secrets.API_KEY }}" > .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/myprofile:latest

      # - name: Deploy to server via SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       echo "✅ Successfully connected to VPS!"
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myprofile:latest
      #       docker stop myprofile || true
      #       docker rm myprofile || true
      #       docker run -d --name myprofile -p 4000:4000 --restart always \
      #         -e API_KEY=${{ secrets.API_KEY }} \
      #         ${{ secrets.DOCKERHUB_USERNAME }}/myprofile:latest
      #       docker system prune -f

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "✅ Successfully connected to VPS!"
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myprofile:latest
            docker stop myprofile || true
            docker rm myprofile || true
            docker run -d --name myprofile -p 4000:4000 --restart always \
              -e API_KEY="${{ secrets.API_KEY }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e APP_PORT="${{ secrets.APP_PORT }}" \
              -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
              -e EMAIL="${{ secrets.EMAIL }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/myprofile:latest
            docker system prune -f
